name: test suite
on: [pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        shell: bash
        if: ${{ runner.os == 'linux' }}
        run: >
          sudo apt-get update
          sudo apt-get install --no-install-recommends libwayland-dev
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
      - run: cargo fmt --all -- --check
